if game.CoreGui:FindFirstChild("TE_EXTRAS")then game.CoreGui.TE_EXTRAS:Destroy()end
local G=Instance.new("ScreenGui",game.CoreGui)G.Name="TE_EXTRAS"G.ResetOnSpawn=false G.IgnoreGuiInset=true
local P,Gr,Rd,DmP,Yl=Color3.fromRGB(170,0,255),Color3.fromRGB(0,255,100),Color3.fromRGB(255,50,50),Color3.fromRGB(85,0,128),Color3.fromRGB(255,255,0)
local function Q(c,p,t)local i=Instance.new(c)if p then i.Parent=p end if t then for k,v in pairs(t)do pcall(function()i[k]=v end)end end return i end
local M=Q("Frame",G,{Size=UDim2.new(0.7,0,0.7,0),Position=UDim2.new(0.5,0,0.5,0),AnchorPoint=Vector2.new(0.5,0.5),BackgroundColor3=Color3.fromRGB(10,5,20),BorderSizePixel=0})
Q("UICorner",M,{CornerRadius=UDim.new(0,8)});Q("UIStroke",M,{Color=P,Thickness=1})
local T=Q("Frame",M,{Size=UDim2.new(1,0,0,30),BackgroundColor3=Color3.fromRGB(15,15,25),BorderSizePixel=0})
Q("TextLabel",T,{Size=UDim2.new(0.9,0,1,0),Text="TE EXTRAS // TERMINAL",TextColor3=P,Font=Enum.Font.Code,TextSize=14,TextXAlignment="Left",BackgroundTransparency=1})
Q("TextButton",T,{Size=UDim2.new(0,30,0,30),Position=UDim2.new(1,-60,0,0),Text="_",TextColor3=Yl,Font=Enum.Font.Code,TextSize=16,BackgroundTransparency=1}).MouseButton1Click:Connect(function()M.Visible=false;MaxR.Visible=true end)
Q("TextButton",T,{Size=UDim2.new(0,30,0,30),Position=UDim2.new(1,-30,0,0),Text="X",TextColor3=Rd,Font=Enum.Font.Code,TextSize=16,BackgroundTransparency=1}).MouseButton1Click:Connect(function()G:Destroy()end)
local MaxR=Q("TextButton",G,{Size=UDim2.new(0,28,0,80),Position=UDim2.new(1,-33,0.5,-40),Text="M\nA\nX",TextColor3=P,Font=Enum.Font.Code,TextSize=10,BackgroundColor3=Color3.fromRGB(12,8,20),Visible=false,ZIndex=100,BorderSizePixel=0})
Q("UICorner",MaxR,{CornerRadius=UDim.new(0,4)});Q("UIStroke",MaxR,{Color=DmP,Thickness=1})
MaxR.MouseButton1Click:Connect(function()MaxR.Visible=false;M.Visible=true end)
local L=Q("Frame",M,{Size=UDim2.new(0.4,0,1,-30),Position=UDim2.new(0,0,0,30),BackgroundColor3=Color3.fromRGB(5,5,10),BorderSizePixel=0})
local O=Q("ScrollingFrame",L,{Size=UDim2.new(1,-4,1,-35),Position=UDim2.new(0,2,0,0),BackgroundTransparency=0,ScrollBarThickness=3,ScrollBarImageColor3=DmP,AutomaticCanvasSize="Y",CanvasSize=UDim2.new(0,0,0,0)})
Q("UIListLayout",O,{Padding=UDim.new(0,1),VerticalAlignment="Bottom",SortOrder=Enum.SortOrder.LayoutOrder})
local I=Q("TextBox",L,{Size=UDim2.new(1,-4,0,30),Position=UDim2.new(0,2,1,-32),BackgroundColor3=Color3.fromRGB(15,15,25),Text="",PlaceholderText="cmd...",TextColor3=P,Font=Enum.Font.Code,TextSize=12,ClearTextOnFocus=false,TextXAlignment="Left",BorderSizePixel=0})
local R=Q("ScrollingFrame",M,{Size=UDim2.new(0.6,0,1,-30),Position=UDim2.new(0.4,0,0,30),BackgroundTransparency=1,ScrollBarThickness=3,AutomaticCanvasSize="Y",ClipsDescendants=true})
Q("UIGridLayout",R,{CellSize=UDim2.new(0,80,0,30),CellPadding=UDim2.new(0,4,0,4),SortOrder=Enum.SortOrder.LayoutOrder})
local C,lC={},0
function log(m,s,c)lC=lC+1;local l=Q("TextLabel",O,{Size=UDim2.new(1,0,0,16),BackgroundTransparency=1,Font=Enum.Font.Code,TextSize=12,TextXAlignment="Left",LayoutOrder=lC})if c then l.Text="  "..m;l.TextColor3=c elseif s==nil then l.Text="  "..m;l.TextColor3=Color3.fromRGB(150,150,170)else l.Text="  "..m..(s and " [OK]" or " [ERR]");l.TextColor3=s and Gr or Rd end task.wait(0.05);O.CanvasPosition=Vector2.new(0,99999)end
local function add(n,f)C[n:lower()]=f;local b=Q("TextButton",R,{Text=n,Font=Enum.Font.Code,TextSize=10,TextColor3=Color3.new(1,1,1),BackgroundColor3=Color3.fromRGB(25,15,45)})b.MouseButton1Click:Connect(function()log(n,true);pcall(f)end)end
add("PLASMA",function()loadstring(game:HttpGet("https://raw.githubusercontent.com/sorta-onYOUTUBE/ute3release/refs/heads/main/PLASMA"))()end)
local PS={["1"]="https://raw.githubusercontent.com/sorta-onYOUTUBE/ute3release/refs/heads/main/list-9k9wste1-2",["2"]="https://raw.githubusercontent.com/sorta-onYOUTUBE/ute3release/refs/heads/main/list-ute2",["3"]="https://raw.githubusercontent.com/sorta-onYOUTUBE/ute3release/refs/heads/main/list-ute3-01",["4"]="https://raw.githubusercontent.com/sorta-onYOUTUBE/ute3release/refs/heads/main/list-ute4legacygui",["5"]="https://raw.githubusercontent.com/sorta-onYOUTUBE/ute3release/refs/heads/main/sTE%205R"}
for i=1,5 do add("P"..i,function()loadstring(game:HttpGet(PS[tostring(i)]))()end)end
add("Invisible",function()loadstring(game:HttpGet("https://raw.githubusercontent.com/Mohamedguguu/invisible-V1-BY-MU/refs/heads/main/Maincode",true))()end)
add("Admin",function()loadstring(game:HttpGet("https://gist.github.com/someunknowndude/38cecea5be9d75cb743eac8b1eaf6758/raw"))()end)
add("InfYield",function()loadstring(game:HttpGet("https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source"))()end)
add("Dex",function()loadstring(game:HttpGet("https://obj.wearedevs.net/2/scripts/Dex%20Explorer.lua"))()end)
add("Spy",function()loadstring(game:HttpGet("https://raw.githubusercontent.com/78n/SimpleSpy/main/SimpleSpyBeta.lua"))()end)
add("Master",function()loadstring(game:HttpGet("https://raw.githubusercontent.com/exxtremestuffs/SimpleSpyV2/master/simple-spy-v3.lua"))()end)
add("Search",function()loadstring(game:HttpGet("https://pastefy.app/cIrUcSTO/raw"))()end)
add("MiniTroll",function()if game.CoreGui:FindFirstChild("Trollem10")then game.CoreGui.Trollem10:Destroy()end local M2=Instance.new("ScreenGui",game.CoreGui)M2.Name="Trollem10"local F=Instance.new("Frame",M2)F.BackgroundColor3=Color3.new(0.1,0.1,0.1)F.Size=UDim2.new(0,200,0,300)F.Position=UDim2.new(0.1,0,0.1,0)F.Active=true F.Draggable=true local T2=Instance.new("TextLabel",F)T2.Size=UDim2.new(1,0,0,30)T2.Text="Troll em 1.0"T2.BackgroundColor3=Color3.fromRGB(60,0,150)T2.TextColor3=Color3.new(1,1,1)local G2=Instance.new("Frame",M2)G2.Size=UDim2.new(0,220,0,320)G2.Position=UDim2.new(0.3,0,0.1,0)G2.BackgroundColor3=Color3.new(0.15,0.15,0.15)G2.Visible=false G2.Active=true G2.Draggable=true local GT=Instance.new("TextLabel",G2)GT.Size=UDim2.new(1,0,0,30)GT.Text="Games"GT.BackgroundColor3=Color3.fromRGB(0,100,150)GT.TextColor3=Color3.new(1,1,1)local function c(tx,p,par,c2)local b=Instance.new("TextButton",par)b.Text=tx b.Position=p b.Size=UDim2.new(0.85,0,0,35)b.BackgroundColor3=c2 or Color3.fromRGB(50,50,50)b.TextColor3=Color3.new(1,1,1)return b end c("IY",UDim2.new(0.07,0,0.15,0),F).MouseButton1Click:Connect(function()loadstring(game:HttpGet("https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source"))()end)c("Dex",UDim2.new(0.07,0,0.3,0),F).MouseButton1Click:Connect(function()loadstring(game:HttpGet("https://raw.githubusercontent.com/peyton2465/Dex/master/out.lua"))()end)c("God HP",UDim2.new(0.07,0,0.45,0),F).MouseButton1Click:Connect(function()if game.Players.LocalPlayer.Character and game.Players.LocalPlayer.Character:FindFirstChild("Humanoid")then game.Players.LocalPlayer.Character.Humanoid.MaxHealth=1e12 game.Players.LocalPlayer.Character.Humanoid.Health=1e12 end end)c("Games",UDim2.new(0.07,0,0.65,0),F,Color3.fromRGB(0,120,0)).MouseButton1Click:Connect(function()G2.Visible=true end)c("Close",UDim2.new(0.07,0,0.82,0),F,Color3.fromRGB(120,0,0)).MouseButton1Click:Connect(function()M2:Destroy()end)c("Inv",UDim2.new(0.07,0,0.12,0),G2).MouseButton1Click:Connect(function()loadstring(game:HttpGet("https://raw.githubusercontent.com/GhostPlayer352/Test4/main/Invisible%20Gui"))()end)c("Pizza",UDim2.new(0.07,0,0.25,0),G2).MouseButton1Click:Connect(function()loadstring(game:HttpGetAsync("https://raw.githubusercontent.com/blueEa1532/thechosenone/refs/heads/main/trollpizzagui"))()end)c("MM2",UDim2.new(0.07,0,0.38,0),G2).MouseButton1Click:Connect(function()loadstring(game:HttpGet("https://raw.smokingscripts.org/vertex.lua"))()end)c("TP",UDim2.new(0.07,0,0.51,0),G2).MouseButton1Click:Connect(function()loadstring(game:HttpGet("https://raw.githubusercontent.com/Telxr/Teleportica/refs/heads/main/Telepo"))()end)c("Fling",UDim2.new(0.07,0,0.64,0),G2).MouseButton1Click:Connect(function()loadstring(game:HttpGet("https://raw.githubusercontent.com/K1LAS1K/Ultimate-Fling-GUI/main/flingscript.lua"))()end)c("Back",UDim2.new(0.07,0,0.85,0),G2).MouseButton1Click:Connect(function()G2.Visible=false end)end)
I.FocusLost:Connect(function(e)if e then local t=I.Text;I.Text="";if t~=""then log(">"..t,nil,Gr)local c2=t:lower()if C[c2]then pcall(C[c2])else log("Unknown: "..c2,false)end end end end)
